// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBawCdSk1rQaxLYy_U5UVS1LShjDGwlMI',
    appId: '1:142573379850:web:97fa8a8a53011172bf5af3',
    messagingSenderId: '142573379850',
    projectId: 'laboratory2-4134b',
    authDomain: 'laboratory2-4134b.firebaseapp.com',
    storageBucket: 'laboratory2-4134b.firebasestorage.app',
    measurementId: 'G-1NMVDLMGXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-3YVWpk51O3v50HnXYiOR7JNkgnP-QI',
    appId: '1:142573379850:android:099b9a830ed65d34bf5af3',
    messagingSenderId: '142573379850',
    projectId: 'laboratory2-4134b',
    storageBucket: 'laboratory2-4134b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdD_CW_xAvA4yiLdyV754zrtB-DVusPYw',
    appId: '1:142573379850:ios:6246efe0ec294575bf5af3',
    messagingSenderId: '142573379850',
    projectId: 'laboratory2-4134b',
    storageBucket: 'laboratory2-4134b.firebasestorage.app',
    iosBundleId: 'com.example.laboratory2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdD_CW_xAvA4yiLdyV754zrtB-DVusPYw',
    appId: '1:142573379850:ios:6246efe0ec294575bf5af3',
    messagingSenderId: '142573379850',
    projectId: 'laboratory2-4134b',
    storageBucket: 'laboratory2-4134b.firebasestorage.app',
    iosBundleId: 'com.example.laboratory2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBawCdSk1rQaxLYy_U5UVS1LShjDGwlMI',
    appId: '1:142573379850:web:04b1081df6e29878bf5af3',
    messagingSenderId: '142573379850',
    projectId: 'laboratory2-4134b',
    authDomain: 'laboratory2-4134b.firebaseapp.com',
    storageBucket: 'laboratory2-4134b.firebasestorage.app',
    measurementId: 'G-DRQFNKH4F6',
  );
}
